### ISSUE TITLE
nilnil off for compat mode?

### ISSUE THREAD

**Issue by brian-vogogo** [ohler55/oj#296]
By default, I think nilnil should be false in compat mode to match JSON.parse.

```ruby
JSON.parse nil
# TypeError: no implicit conversion of nil into String
#	from /Users/brian/.rvm/gems/ruby-2.2.3@kyc-admin/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
#	from /Users/brian/.rvm/gems/ruby-2.2.3@kyc-admin/gems/json-1.8.3/lib/json/common.rb:155:in `new'
#   ...

Oj.mimic_JSON
# { :nilnil => true ... }

JSON.parse nil
# => nil               # <-- expected exception
```

**Comment by ohler55** [comment]
Have you checked this with active or rails installed? If JSON consistently raises an exception both by itself and when with rails gems installed I'd be glad to change the default for the mimic mode.

**Comment by brian-vogogo** [comment]
Does this help?

irb without rails, without oj:
```ruby
ActiveRecord::Base
# NameError: uninitialized constant ActiveRecord
# 	from (irb):1
# 	from /Users/brian/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'require 'json'

JSON.parse nil
# TypeError: no implicit conversion of nil into String
# 	from /Users/brian/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
# 	from /Users/brian/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `new'
# 	from /Users/brian/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
# 	from (irb):3
# 	from /Users/brian/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

Rails console, with rails, without oj:
```ruby
ActiveRecord::Base
# ActiveRecord::Base

JSON.parse nil
# TypeError: no implicit conversion of nil into String
# 	from /Users/brian/.rvm/gems/ruby-2.2.3@kyc-admin/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
# 	from /Users/brian/.rvm/gems/ruby-2.2.3@kyc-admin/gems/json-1.8.3/lib/json/common.rb:155:in `new'
```

**Comment by ohler55** [comment]
Fair enough. I'll make the change.

**Comment by ohler55** [comment]
Is this still an issue?

**Comment by ohler55** [comment]
No response. I believe it is fixed.
