### ISSUE TITLE
"NoMemoryError: Too deeply nested." after updating to 2.18.0

### ISSUE THREAD

**Issue by snoopie** [ohler55/oj#325]
Hi, I get the following error after updating oj to v. 2.18.0:
```
NoMemoryError: Too deeply nested.
```

the code I am executing is:
```
Oj.dump(object, :mode => :compat, :time_format => :ruby, :ascii_only => false)
```

It starts working again after adding new option:
```
Oj.dump(object, :mode => :compat, :time_format => :ruby, :ascii_only => false, :use_as_json => true)
```

Could you please explain if it's correct behaviour and if so why new ```use_as_json``` option has to be true? Thanks!

**Comment by ohler55** [comment]
Can you describe the object being dumped? It sounds like it may have circular references. If that is the case then the as_json() method probably does a custom encoding to avoid the circular reference. That would be expected. Give me details on the object if possible and I can probably should you where the circular reference is.

**Comment by ohler55** [comment]
The use_as_json option was added in the release so if you want to simply go back to what you had before set it to true. If you want to dig deeper then we can do that but it will involve some experimenting.

**Comment by bmesuere** [comment]
I have similar issues. After a recent gem update I get the same error message where everything worked fine before:

```
2.3.3p222 :023 > Proteome.proteomes.limit(1)
  Proteome Load (0.6ms)  SELECT  DISTINCT proteomes.name as name, proteomes.id, proteomes.proteome_accession_number as proteome_accession, proteomes.type_strain, proteomes.reference_proteome, lineages.species as species_id, lineages.genus as genus_id, lineages.order as order_id, lineages.class as class_id FROM `proteomes` INNER JOIN `lineages` ON `lineages`.`taxon_id` = `proteomes`.`taxon_id` LIMIT 1
 => #<ActiveRecord::Relation [#<Proteome id: 1, type_strain: "\x00", reference_proteome: "\x01", name: "Frog virus 3 (isolate Goorha)">]> 
2.3.3p222 :024 > Oj.dump(Proteome.proteomes.limit(1), mode: :compat)
NoMemoryError: Too deeply nested.

	from (irb):24:in `dump'
	from (irb):24
	from /Users/bart/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/bart/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/bart/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/bart/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/bart/.rvm/gems/ruby-2.3.3/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
2.3.3p222 :025 > Oj.dump(Proteome.proteomes.limit(1), mode: :compat, :use_as_json => true)
  Proteome Load (0.6ms)  SELECT  DISTINCT proteomes.name as name, proteomes.id, proteomes.proteome_accession_number as proteome_accession, proteomes.type_strain, proteomes.reference_proteome, lineages.species as species_id, lineages.genus as genus_id, lineages.order as order_id, lineages.class as class_id FROM `proteomes` INNER JOIN `lineages` ON `lineages`.`taxon_id` = `proteomes`.`taxon_id` LIMIT 1
 => "[{\"id\":1,\"type_strain\":false,\"reference_proteome\":true,\"name\":\"Frog virus 3 (isolate Goorha)\",\"proteome_accession\":\"UP000008770\",\"species_id\":10493,\"genus_id\":10492,\"order_id\":null,\"class_id\":null}]" 
```

Is there a way to set `use_as_json` to true as the default for my entire application?

**Comment by ohler55** [comment]
You can use the :use_as_json option in the Oj.default_options.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by snoopie** [comment]
@ohler55 Sure, I'll close it. Maybe it is worth mentioning this problem(or, rather, compatibility issue) in the release notes?

**Comment by ohler55** [comment]
It is a continual problem. I work around it and active support figures out how to break it again. Adding something to the docs might be worthwhile. There is already a mention of the use_as_json option in the release notes though.
