### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by stereobooster** [ohler55/oj#367]
See https://github.com/stereobooster/ruby-json-benchmark/blob/latest-oj/test_report.txt

**Comment by ohler55** [comment]
What was being run to get that?

**Comment by stereobooster** [comment]
`bundle exec ruby compatibility_test.rb`

**Comment by ohler55** [comment]
Where is the compatibility_test.rb? Is that in you benchmarks?

**Comment by stereobooster** [comment]
Yes

**Comment by ohler55** [comment]
Thanks I am still wrapped up in go code. Finishing up for the day though.

**Comment by ohler55** [comment]
I get this:
```
big ruby-json-benchmark (latest-oj)> bundle exec ruby compatibility_test.rb
/Users/ohler/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/time.rb:50:in `*': ActiveSupport::Duration can't be coerced into Integer (TypeError)
	from /Users/ohler/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.1.16/lib/active_support/core_ext/numeric/time.rb:50:in `days'
	from /Users/ohler/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.1.16/lib/active_support/core_ext/integer/time.rb:36:in `months'
	from /Users/ohler/git/ruby-json-benchmark/test_data.rb:87:in `<top (required)>'
	from compatibility_test.rb:3:in `require'
	from compatibility_test.rb:3:in `<main>'
```

Seems to be using ActiveSupport 4 and not 5.

**Comment by stereobooster** [comment]
try `wwtd` command it will iterate over all ruby/gem combinations.

**Comment by ohler55** [comment]
```
big ruby-json-benchmark (latest-oj)> wwtd
Ignoring: branches, cache, langauge, sudo
MISSING_RUBY_VERSION gemfile: gemfiles/4.1.16.gemfile rvm: 2.2.6
START gemfile: gemfiles/4.1.16.gemfile rvm: 2.3.3
bundle install --deployment --path /Users/ohler/git/ruby-json-benchmark/vendor/bundle --quiet
/Users/ohler/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /Users/ohler/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
	from /Users/ohler/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
FAILURE gemfile: gemfiles/4.1.16.gemfile rvm: 2.3.3
```
and more like that

**Comment by ohler55** [comment]
By the way, there should be some changes in the test files once things are no crashing. I'll help with that.

**Comment by stereobooster** [comment]
```
rbenv local 2.2.6
gem install bundler
rbenv local 2.3.3
gem install bundler
rbenv local 2.4.0
gem install bundler
rbenv local --unset
```

**Comment by ohler55** [comment]
If you use ```Oj::Rails.encode(val)``` instead of ```Oj.dump(val, mode: :rails)``` there is no crash. You should use that anyway but I will get the other fixed. Looking now.

**Comment by ohler55** [comment]
Pull the bench branch and give it a try although I still recommend the ```Oj::Rails.encode(val)``` call. More direct.

**Comment by stereobooster** [comment]
Updated: no more segmentation fault. Strange thing there are errors in compatibility.

**Comment by ohler55** [comment]
Even with Ruby 2.4 and ActiveSupport 5?

**Comment by stereobooster** [comment]
Strange but yes

**Comment by ohler55** [comment]
I'll take a look at the compatibility_test.rb later today and see where the mismatch is.

**Comment by ohler55** [comment]
I think the compatibility matrix should show
1. json gem vs Oj compat mode or maybe with mimic_JSON on
2. Rails vs Oj::Rails.encode and decode
3. MessagePack
4. Maybe for interest sake, json gem vs Rails

The json gem and Rails to_json are not the same. Rails encodes differently then the gem. They battle it out with the as_json implementations depending on which is loaded first. I think the tests should run through each separately with a ```Object.send(:remove_const, :JSON)``` after the json gem run and similar for ActiveSupport.

**Comment by stereobooster** [comment]
If you will release branch with fix, we can close this ticket. For results mismatch I can open another ticket.

**Comment by ohler55** [comment]
Released

**Comment by ohler55** [comment]
Before opening a ticket here for the mismatch lets get the compatibility_test.rb corrected. Would you like help with that?

**Comment by stereobooster** [comment]
Updated

```
+---------------------------------+----------------------+--------------+---------+------------+-----------------+
| class                           | JSON.generate quirks | JSON.to_json | Oj.dump | Oj to_json | msgpack "rails" |
+---------------------------------+----------------------+--------------+---------+------------+-----------------+
| Regexp                          | 👌                   | 👌           | 👌      | 👌         | 👌              |
| FalseClass                      | 👌                   | 👌           | 👌      | 👌         | 👌              |
| NilClass                        | 👌                   | 👌           | 👌      | 👌         | 👌              |
| Object                          | ❌                   | ❌           | 👌      | 👌         | 👌              |
| TrueClass                       | 👌                   | 👌           | 👌      | 👌         | 👌              |
| String                          | 👌                   | 👌           | 👌      | 👌         | 👌              |
| StringChinese                   | 👌                   | 👌           | 👌      | 👌         | 👌              |
| StringSpecial                   | ❌                   | ❌           | ❌      | 👌         | 👌              |
| StringSpecial2                  | 👌                   | 👌           | 👌      | 👌         | 👌              |
| StringSpecial3                  | 👌                   | 👌           | 👌      | 👌         | 👌              |
| Numeric                         | 👌                   | 👌           | 👌      | 👌         | 👌              |
| Symbol                          | 👌                   | 👌           | 👌      | 👌         | 👌              |
| Time                            | ❌                   | ❌           | 👌      | 👌         | 👌              |
| Array                           | 👌                   | 👌           | 👌      | 👌         | 👌              |
| Hash                            | 👌                   | 👌           | 👌      | 👌         | 👌              |
| HashNotEmpty                    | 👌                   | 👌           | 👌      | 👌         | 👌              |
| Date                            | 👌                   | 👌           | 👌      | 👌         | 👌              |
| DateTime                        | ❌                   | ❌           | 👌      | 👌         | 👌              |
| Enumerable                      | ❌                   | ❌           | 👌      | 👌         | 👌              |
| BigDecimal                      | ❌                   | ❌           | 👌      | 👌         | 👌              |
| BigDecimalInfinity              | ❌                   | ❌           | 👌      | 👌         | 👌              |
| Struct                          | ❌                   | ❌           | 👌      | 👌         | 👌              |
| Float                           | 👌                   | 👌           | 👌      | 👌         | 👌              |
| FloatInfinity                   | 💀                   | 💀           | 👌      | 👌         | ❌              |
| Range                           | 👌                   | 👌           | 👌      | 👌         | 👌              |
| Complex                         | 👌                   | 👌           | ❌      | 👌         | 👌              |
| Exception                       | ❌                   | ❌           | 👌      | 👌         | 👌              |
| OpenStruct                      | ❌                   | ❌           | 👌      | 👌         | 👌              |
| Rational                        | 👌                   | 👌           | ❌      | 👌         | 👌              |
| Process::Status                 | ❌                   | ❌           | 👌      | 👌         | 👌              |
| ActiveSupport::TimeWithZone     | ❌                   | ❌           | 👌      | 👌         | 👌              |
| ActiveModel::Errors             | ❌                   | ❌           | 👌      | 👌         | 👌              |
| ActiveSupport::Duration         | ❌                   | ❌           | 👌      | 👌         | 👌              |
| ActiveSupport::Multibyte::Chars | 👌                   | ❌           | 👌      | 👌         | 👌              |
| ActiveRecord::Relation          | ❌                   | ❌           | 👌      | 👌         | 👌              |
| ActiveRecord                    | ❌                   | ❌           | 👌      | 👌         | 👌              |
+---------------------------------+----------------------+--------------+---------+------------+-----------------+
```

**Comment by ohler55** [comment]
From looking at compatibility_test.rb I see those are comparisons of various encodings against Rails. Thats excellent.

**Comment by ohler55** [comment]
Although you should use the Oj::Rails.encode or the ActiveSupport.encode once Oj::Rails.set_encoder is called.

**Comment by stereobooster** [comment]
I call to_json before and after Oj::Rails.set_encoder so it is fair enough
