### ISSUE TITLE
TypeError: wrong argument type Integer (expected String) when setting `indent` option

### ISSUE THREAD

**Issue by PetrKaleta** [ohler55/oj#381]
`oj (3.0.6)`

`Oj.dump({foo: Time.now}, indent: 2)`

**Comment by ohler55** [comment]
That is not Oj complaining. My guess is you have set the defaults to either use to_json or are using the :compat mode which call the json gem to_json method on the Hash class. Oj will accept either a string or an integer but the json gem monkey patched to_json methods only accept a string.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by ohler55** [comment]
No response. Closing.

**Comment by evanleck** [comment]
Just ran into this issue as well but I have the following configuration options with Oj 3.3.5:

```ruby
Oj.default_options = {
  bigdecimal_load: :bigdecimal,
  circular: false,
  class_cache: true,
  mode: :json
}
```

For context, I'm basically trying to mimic the output of `JSON.pretty_generate` but using Oj instead of the json gem. Seems like the `:indent` option gets me 90% there but I encounter this error occasionally.

**Comment by ohler55** [comment]
First lets identify where the exception is being raised. Please provide a stack track to see what method is raising the exception.

**Comment by evanleck** [comment]
Here's what I've got (some path stuff removed for brevity):

```
TypeError: wrong argument type Integer (expected String)
  lib/debuggers/models/http_adapter.rb:60:in `initialize'
  lib/debuggers/models/http_adapter.rb:60:in `new'
  lib/debuggers/models/http_adapter.rb:60:in `to_json'
  lib/debuggers/models/http_adapter.rb:60:in `dump'
  lib/debuggers/models/http_adapter.rb:60:in `fetch'
  models/api_adapter.rb:145:in `fetch'
  lib/cachers/models/api_adapter.rb:112:in `fetch'
  models/http_adapter.rb:48:in `get'
  models/api_adapter.rb:66:in `get'
  helpers/products.rb:16:in `block in call'
  helpers/products.rb:14:in `delete'
  helpers/products.rb:14:in `call'
  helpers/participant.rb:47:in `call'
  helpers/api.rb:12:in `call'
  helpers/service.rb:20:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/syro-3.0.1/lib/syro.rb:371:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
  middleware/not_found.rb:25:in `call'
  middleware/authorize.rb:24:in `call'
  middleware/authenticate.rb:96:in `call'
  middleware/csrf.rb:35:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
  middleware/i18n.rb:44:in `call'
  middleware/browser.rb:22:in `call'
  middleware/branded.rb:71:in `call'
  middleware/headers.rb:39:in `call'
  middleware/method_override.rb:17:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
  middleware/logger.rb:33:in `block in call'
  .rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
  middleware/logger.rb:32:in `call'
  middleware/correlation_id.rb:20:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
  middleware/health_check.rb:22:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/static.rb:149:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:153:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
  .rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

And the code around line 60 is (where `messages` is just an array and `response` is a `Typhoeus::Response`):

```ruby
if response.headers['Content-Type']&.include?('application/json')
  messages.push format("\e[1mResponse Body:\e[0m\r\n%s", Oj.dump(Oj.load(response.body), indent: 2))
end
```

What's weird is that I don't see Oj in there at all but this error only started when I made the change to use `indent: 2` instead of `JSON.pretty_generate`.

**Comment by ohler55** [comment]
What does the http_adapter expect in the initialize call? I would also check the http_adapter to_json call and see that the code looks like. If you can included that code it would help.

**Comment by evanleck** [comment]
I feel like the stack trace isn't giving us a lot of info because there's no to_json method in http_adapter. The initialize method just takes a string/URI to set as the base for further HTTP requests.

Here's the HTTPAdapter class:

```ruby
##
# Adapter class around Typhoeus.
#
# Simplifies most HTTP calls (e.g. GET or POST) with simpler methods that
# accept a Hash and format the request appropriately. It currently supports
# sending requests as a URL encoded form or as a JSON string. We also
# support sending multipart requests via a special `multipart` method.
#
class HTTPAdapter
  # Default request headers.
  DEFAULT_HEADERS = {
    'Accept' => 'application/json',
    'Connection' => 'keep-alive',
    'User-Agent' => 'Harmony Web Frontend v1'
  }.freeze

  # Default options passed to Typhoeus.
  DEFAULT_OPTIONS = {
    accept_encoding: 'gzip',
    connecttimeout: 10,
    headers: DEFAULT_HEADERS,
    ssl_verifypeer: Environment.verify_peer?,
    timeout: 120
  }.freeze

  # Initialize a new instance.
  #
  # @param base [String, URI] a URI-compliant base URL to make requests
  #   against or an existing URI object.
  def initialize(base)
    @base = URI.parse(base.to_s)
  end

  # Perform an HTTP GET request.
  #
  # @param path [String] the path to GET.
  # @param params [Hash] a hash of params to add as a query string.
  # @return [Decorators::Response]
  def get(path, params = {})
    fetch request(path, :get, options(params, :query))
  end

  # Perform an HTTP POST request.
  #
  # @param path [String] the path to POST.
  # @param params [Hash] a hash of params to add to the request body.
  # @param as [Symbol] the form to send the request as. Determines
  #   content-type and the format of the request body.
  # @return [Decorators::Response]
  def post(path, params = {}, as: :json)
    fetch request(path, :post, options(params, as))
  end

  # Perform an HTTP DELETE request.
  #
  # @param path [String] the path to DELETE.
  # @return [Decorators::Response]
  def delete(path)
    fetch request(path, :delete)
  end

  # Perform an HTTP PATCH request.
  #
  # @param path [String] the path to PATCH.
  # @param params [Hash] a hash of params to add to the request body.
  # @param as [Symbol] the form to send the request as. Determines
  #   content-type and the format of the request body.
  # @return [Decorators::Response]
  def patch(path, params = {}, as: :form)
    fetch request(path, :patch, options(params, as))
  end

  # Perform an HTTP PUT request.
  #
  # @param path [String] the path to POST.
  # @param params [Hash] a hash of params to add to the request body.
  # @param as [Symbol] the form to send the request as. Determines
  #   content-type and the format of the request body.
  # @return [Decorators::Response]
  def put(path, params = {}, as: :json)
    fetch request(path, :put, options(params, as))
  end

  # Perform a multipart POST request.
  #
  # @param path [String] the path to POST.
  # @param file [Hash] hash with `:tempfile` and `:type` keys which will get
  #   passed to Rack::Multipart::UploadedFile#new.
  # @return [Decorators::Response]
  def multipart(path, file)
    body = Rack::Multipart::Generator.new(
      'file' => Rack::Multipart::UploadedFile.new(file[:tempfile].path, file[:type])
    ).dump

    fetch request(path, :post, options({ body: body }, :multipart))
  end

  # Generate a new Typhoeus::Request object.
  #
  # @param path [String]
  #   The base path to send our request to.
  # @param method [Symbol]
  #   The request method.
  # @param options [Hash]
  #   Any options to pass to Typhoeus.
  #
  # @return [Typhoeus::Request]
  def request(path, method, options = DEFAULT_OPTIONS)
    Typhoeus::Request.new(@base.merge(URI.parse(path)), options.merge(method: method))
  end

  # Set up options and headers to send with any given request.
  #
  # @param params [Hash]
  #   The parameters to encode.
  # @param as [Symbol]
  #   The format to encode the params as.
  #
  # @return [Hash]
  #   A Hash suitable for passing to Typhoeus::Request.new.
  def options(params, as)
    case as
    when :query
      { params: params,
        headers: DEFAULT_HEADERS }
    when :json
      { body: Oj.dump(params),
        headers: DEFAULT_HEADERS.merge('Content-Type' => 'application/json') }
    when :multipart
      { body: params.fetch(:body),
        headers: DEFAULT_HEADERS.merge('Content-Type' => "multipart/form-data; boundary=#{ Rack::Multipart::MULTIPART_BOUNDARY }") }
    else
      { body: URI.encode_www_form(params),
        headers: DEFAULT_HEADERS.merge('Content-Type' => 'application/x-www-form-urlencoded') }
    end
  end

  private

  # Perform the request and returned the parsed response.
  #
  # @param request [Typhoeus::Request] the request to process.
  # @return [Decorators::Response] the decorated response.
  def fetch(request)
    Decorators::Response.new(request.run)
  end
end
```

And the `Decorators::Response` class:

```ruby
##
# A decorator around Typhoeus::Response.
#
# Expects a Typhoeus::Response as the initialization argument and sets up a
# few instance variables.
#
class Response < SimpleDelegator
  attr_reader :alert, :body, :failed, :response, :succeeded

  def initialize(response)
    @response = response
    @body =
      case response.headers['Content-Type']
      when /json/
        Oj.load(response.body)
      else
        response.body
      end

    # Things we check a few different times.
    dig = @body.respond_to?(:dig)

    # Alert content or a generic, non-empty response.
    @alert =
      # CORE error with a message and/or errors.
      if dig && @body.key?('status')
        { danger: @body.dig('status', 'message'),
          errors: @body.dig('status', 'errors') }

      # Layer 7 returns a different structure than CORE.
      elsif dig && @body.key?('ErrorID')
        { danger: format('Error Code: %s - %s', @body.dig('ErrorCode'), @body.dig('Advice')) }

      # No dice, just keep it generic.
      else
        { danger: nil, errors: [{}] }
      end

    # Response is valid and, if applicable, the status code is 0.
    @succeeded =
      if dig && @body.key?('status')
        @response.success? && @body.dig('status', 'code') == 0 # rubocop:disable Style/NumericPredicate
      else
        @response.success?
      end

    # Added to simplify checks and filtering on arrays of response objects.
    @failed = !@succeeded

    # Delegate all further method calls to the body of the response.
    __setobj__(@body)
  end
end
```

I'm trying to better isolate the issue and I'll let you know if I turn anything else up.

**Comment by evanleck** [comment]
Popping open a REPL at the point where it's failing and poking around gives me this:

```
>> response.class
=> Typhoeus::Response
>> response.code
=> 200
>> response.body.class
=> String
>> Oj.load(response.body).class
=> Hash
>> Oj.dump(Oj.load(response.body))
=> _Works fine_
>> Oj.dump(Oj.load(response.body), indent: 2)
!! #<TypeError: wrong argument type Integer (expected String)>
```

**Comment by evanleck** [comment]
Interestingly, though I have this configuration loaded early in my code:

```ruby
Oj.default_options = {
  bigdecimal_load: :bigdecimal,
  circular: false,
  class_cache: true,
  mode: :json
}
```

I see the following from that same REPL:

```
>> Oj.default_options
=> {:indent=>0, :second_precision=>9, :circular=>false, :class_cache=>true, :auto_define=>false, :symbol_keys=>false, :bigdecimal_as_decimal=>true, :use_to_json=>false, :use_to_hash=>false, :use_as_json=>false, :nilnil=>false, :empty_string=>true, :allow_gc=>true, :quirks_mode=>true, :allow_invalid_unicode=>false, :allow_nan=>true, :float_precision=>16, :mode=>:compat, :escape_mode=>:json, :time_format=>:unix, :bigdecimal_load=>:bigdecimal, :create_id=>"json_class", :space=>nil, :space_before=>nil, :object_nl=>nil, :array_nl=>nil, :nan=>:auto, :omit_nil=>false, :hash_class=>nil, :array_class=>nil}
```

Which shows the mode is compat, not json.

**Comment by ohler55** [comment]
You are correct, something is not adding up. The file you posted, was it lib/debuggers/models/http_adapter.rb or a different http_adapter?

**Comment by evanleck** [comment]
Sorry, no that's the main http_adapter class, here's the debugger:

```ruby
# encoding: UTF-8
# frozen_string_literal: true
require 'lib/environment'
require 'lib/logger'
require 'models/http_adapter'

module Harmony # :nodoc:
  module Debuggers
    module Models
      # Debugger for {Harmony::Models::HTTPAdapter our HTTP adapter}.
      module HTTPAdapter
        include Harmony::Logger

        # Fetch is the single entrypoint to  actually perform a request. See
        # {Harmony::Models::HTTPAdapter#fetch} for more.
        def fetch(request)
          messages = []

          # This is pretty verbose, so we hide it away by default.
          if Environment.debug_http?
            messages.push "\e[1mRequest Headers:\e[0m"
            request.options[:headers].each do |header, value|
              messages.push format('  %s: %s', header, value)
            end

            if request.options[:body]
              formatted_body =
                case request.options[:headers]['Content-Type']
                when /json/
                  Oj.dump(Oj.load(request.options[:body]), indent: 2)
                when /form-urlencoded/
                  request.options[:body].split('&').map do |pair|
                    pair.split('=').join(' = ')
                  end.join("\r\n").prepend("\r\n").concat("\r\n")
                when /multipart/
                  "\r\n\e[3mMultipart\e[0m\r\n"
                else
                  request.options[:body]
                end

              messages.push format("\e[1mRequest Body:\e[0m\r\n%s", formatted_body)
            end
          end

          # Capture the response.
          decorated = super(request)

          # This is pretty verbose, so we hide it away by default.
          if Environment.debug_http?
            response = decorated.response

            messages.push format("\e[1mResponse Code:\e[0m %s", response.code)
            messages.push "\e[1mResponse Headers:\e[0m"

            response.headers.each do |header, value|
              messages.push format('  %s: %s', header, value)
            end

            if response.headers['Content-Type']&.include?('application/json')
              messages.push format("\e[1mResponse Body:\e[0m\r\n%s", Oj.dump(Oj.load(response.body), indent: 2))
            else
              messages.push format("\e[1mResponse Body:\e[0m\r\n%s", response.body)
            end
          end

          # Our initial message including duration.
          messages.unshift format('http="%s %s" took=%ims', request.options[:method].upcase, request.base_url, decorated.response.time * 1000)

          # Log our messages.
          logger.debug do
            messages.join("\r\n")
          end

          decorated
        end
      end
    end
  end

  # Prepend our methods and debug output if appropriate.
  if Environment.debug? || Environment.debug_http?
    Models::HTTPAdapter.prepend(Debuggers::Models::HTTPAdapter)
  end
end
```

**Comment by ohler55** [comment]
Ok, how about breaking the ```Oj.dump(Oj.load(response.body))``` into 2 lines and then printing out the class of the ```Oj.load()``` call.

**Comment by evanleck** [comment]
Yeah, I did that [in the REPL and it's a Hash](https://github.com/ohler55/oj/issues/381#issuecomment-322300688). Breaking it into 2 lines didn't affect the behavior at all.

**Comment by ohler55** [comment]
What is in the Hash? Just simple types or some more complex objects?

**Comment by evanleck** [comment]
All just simple types, yeah.

**Comment by ohler55** [comment]
What happens if you can ```to_json``` on that object? With and without the indent option and with either a string or a number as an argument.

**Comment by evanleck** [comment]
`to_json` on the object returned from `Oj.load(response.body)` seems to work but it doesn't contain any formatting. Calling `to_json(2)` or `to_json('  ')` seems to yield the same result, just a flat JSON string without any indentation. Is that what you wanted me to try?

**Comment by evanleck** [comment]
It seems that removing the `mode: :json` in my default configuration did the trick... I'm still not sure what the root cause was though :/

**Comment by ohler55** [comment]
```to_json(indent: 2)``` and ```to_json(indent: "  ")```

**Comment by ohler55** [comment]
The ```:json``` mode will call any ```to_json``` methods on objects such as Hash. That is what the JSON gem does so Oj mimics that behavior in the ```:json``` mode. Oj also passes in the options to the ```to_json``` call. The JSON gem has added the ```to_json``` method to Hash (monkey-patched). That method expects a string value for the ```:indent``` option.

**Comment by evanleck** [comment]
I think that was the disconnect for me; I didn't realize that's what the `:json` mode was doing but that makes sense. Thanks so much for helping me debug, sorry to waste your time with my own misunderstanding!

**Comment by ohler55** [comment]
It was worth it to help your understanding. :-)
