### ISSUE TITLE
Segmentation Fault on Oj.dump for NoMethodError.new

### ISSUE THREAD

**Issue by ssteeg-mdsol** [ohler55/oj#404]
I'm running into a segmentation fault when running `Oj.dump(NoMethodError.new)`

### Env:
- macOS El Capitan 10.11.6
- oj 3.3.0
- ruby 2.4.1

### How to reproduce :
```rb
require 'oj'
Oj.dump(NoMethodError.new)
```

### Output:
```
(irb):2: [BUG] Segmentation fault at 0x00000000000000
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0020 p:---- s:0100 e:000099 CFUNC  :dump
c:0019 p:0022 s:0095 e:000094 EVAL   (irb):2 [FINISH]
c:0018 p:---- s:0092 e:000091 CFUNC  :eval
c:0017 p:0025 s:0084 e:000083 METHOD /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87
c:0016 p:0027 s:0076 e:000074 METHOD /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/context.rb:381
c:0015 p:0024 s:0069 e:000068 BLOCK  /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:493
c:0014 p:0041 s:0060 e:000059 METHOD /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:627
c:0013 p:0011 s:0054 e:000053 BLOCK  /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:490
c:0012 p:0128 s:0049 e:000048 BLOCK  /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:246 [FINISH]
c:0011 p:---- s:0045 e:000044 CFUNC  :loop
c:0010 p:0009 s:0041 e:000040 BLOCK  /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232 [FINISH]
c:0009 p:---- s:0038 e:000037 CFUNC  :catch
c:0008 p:0018 s:0033 e:000032 METHOD /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231
c:0007 p:0037 s:0029 E:000f10 METHOD /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:489
c:0006 p:0008 s:0025 e:000024 BLOCK  /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:430 [FINISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :catch
c:0004 p:0075 s:0017 E:001078 METHOD /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:429
c:0003 p:0118 s:0012 e:000011 METHOD /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:385
c:0002 p:0023 s:0006 e:000005 EVAL   /Users/ssteeg/.rbenv/versions/2.4.1/bin/irb:11 [FINISH]
c:0001 p:0000 s:0003 E:000060 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/ssteeg/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:385:in `start'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:429:in `run'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:429:in `catch'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb:493:in `block (2 levels) in eval_input'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/context.rb:381:in `evaluate'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `evaluate'
/Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'
(irb):2:in `irb_binding'
(irb):2:in `dump'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000062 rbx: 0x00007fff5be0eeb8 rcx: 0x0000000000000000
 rdx: 0x0000000000000008 rdi: 0x00000001044a19ab rsi: 0x0000000000000000
 rbp: 0x00007fff5be0eb60 rsp: 0x00007fff5be0eb60  r8: 0x00007fcb4bf2dc80
  r9: 0x00000001044a5740 r10: 0x0000000000000005 r11: 0x00007fff9547d180
 r12: 0x0000000000000000 r13: 0x0000000000000000 r14: 0x0000000000000001
 r15: 0x00007fcb4c80e7a0 rip: 0x00007fff9550b817 rfl: 0x0000000000010202

-- C level backtrace information -------------------------------------------
0   ruby                                0x0000000103fbb3e8 rb_vm_bugreport + 136
1   ruby                                0x0000000103e53d4e rb_bug_context + 510
2   ruby                                0x0000000103f36938 sigsegv + 72
3   libsystem_platform.dylib            0x00007fff9550c52a _sigtramp + 26
4   libsystem_platform.dylib            0x00007fff9550b817 _platform_strcmp + 23

-- Other runtime information -----------------------------------------------

* Loaded script: irb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin15/enc/encdb.bundle
    5 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin15/enc/trans/transdb.bundle
    6 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/unicode_normalize.rb
    7 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin15/rbconfig.rb
    8 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/compatibility.rb
    9 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/defaults.rb
   10 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/deprecate.rb
   11 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/errors.rb
   12 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/version.rb
   13 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/requirement.rb
   14 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/platform.rb
   15 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/basic_specification.rb
   16 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/stub_specification.rb
   17 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/util/list.rb
   18 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin15/stringio.bundle
   19 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb
   20 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/exceptions.rb
   21 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/dependency.rb
   22 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   23 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb
   24 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   25 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb
   26 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/path_support.rb
   27 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/version.rb
   28 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/core_ext/name_error.rb
   29 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/levenshtein.rb
   30 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/jaro_winkler.rb
   31 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checker.rb
   32 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/delegate.rb
   33 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   34 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   35 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   36 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   37 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/null_checker.rb
   38 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/formatter.rb
   39 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean.rb
   40 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/e2mmap.rb
   41 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/init.rb
   42 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/workspace.rb
   43 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/inspector.rb
   44 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/output-method.rb
   45 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/context.rb
   46 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/extend-command.rb
   47 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/notifier.rb
   48 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/slex.rb
   49 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-token.rb
   50 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ruby-lex.rb
   51 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/src_encoding.rb
   52 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/magic-file.rb
   53 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin15/readline.bundle
   54 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/input-method.rb
   55 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/locale.rb
   56 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb.rb
   57 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/completion.rb
   58 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/ext/save-history.rb
   59 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin15/bigdecimal.bundle
   60 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/version.rb
   61 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/bag.rb
   62 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/easy_hash.rb
   63 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/error.rb
   64 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/ostruct.rb
   65 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/mimic.rb
   66 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/saj.rb
   67 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/schandler.rb
   68 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin15/date_core.bundle
   69 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/date.rb
   70 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/2.4.0/time.rb
   71 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj/oj.bundle
   72 /Users/ssteeg/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oj-3.3.0/lib/oj.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

[1]    11017 abort      irb
```

Thanks for any help!

**Comment by ohler55** [comment]
I'll take a look. There is special code for handling Exceptions since they are not normal Ruby objects. It might take a day or two to get to it but it will get fixed.

**Comment by ohler55** [comment]
Found a few minutes before taking off. Try the 'invisible' branch. I'll release when I get a chance if it works for you.

**Comment by ssteeg-mdsol** [comment]
Thanks for fixing it so quickly! The above case seems to be fixed, look forward to the release of it.

**Comment by ohler55** [comment]
Released.

**Comment by ohler55** [comment]
Can this be closed?

**Comment by ohler55** [comment]
No further response but last comment was that it was fixed. Clsoing.
