### ISSUE TITLE
omit_nil in rails mode

### ISSUE THREAD

**Issue by rgraff** [ohler55/oj#533]
If I'm reading the docs right, the omit_nil option should work in rails mode but I'm on gem version 3.7.11

```
Oj.dump({a: 1, b: nil}, mode: :rails, omit_nil: true)
=> "{\"a\":1,\"b\":null}"
```

Am I doing something wrong?

**Comment by ohler55** [comment]
Looks like a bug. I'll get it fixed tonight or over the weekend. The option works in all other modes. Not sure why no one caught it before now.

**Comment by ohler55** [comment]
Please try the `omit_nil` branch.

**Comment by rgraff** [comment]
I'm getting a LoadError. I think the issue is specific to my environment which is using spring and bootsnap. I'll take another look later today. 

-Robert

```
› bundle exec rails console
/Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require': cannot load such file -- oj/oj (LoadError)
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:80:in `register'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:36:in `rescue in require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:25:in `require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/rgraff/Development/goldstar/vendor/cache/oj-bcf892908e8f/lib/oj.rb:21:in `<main>'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	from /Users/rgraff/Development/goldstar/config/application.rb:7:in `<top (required)>'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/rgraff/.gem/ruby/2.4.3/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/rgraff/.rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rgraff/.rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by rgraff** [comment]
Confirmed that it works. I had to delete the gem from vendor/cache and re-bundle to fix the LoadError above. I can't explain why.

Confirmed that it works in a fresh rails (5.1.7) in all the versions of ruby I have installed. No issues.

```
2.3.7p456 in test-oj/ on master 
› bundle exec rails console
Loading development environment (Rails 5.1.7)
irb(main):001:0> require 'oj'
=> false
irb(main):002:0> Oj.dump({a: 1, b: nil}, mode: :rails)
=> "{\"a\":1,\"b\":null}"
irb(main):003:0> Oj.dump({a: 1, b: nil}, mode: :rails, omit_nil: true)
=> "{\"a\":1}"
```

Are you going to do a new release?

**Comment by ohler55** [comment]
yes, as soon as the travis build completes.

**Comment by ohler55** [comment]
Released

**Comment by rgraff** [comment]
Thanks! Closing issue.
