### ISSUE TITLE
An error occurred while installing oj (3.8.1)

### ISSUE THREAD

**Issue by Fudoshiki** [ohler55/oj#549]
3.8.0 work fine

**macOS Catalina 10.15 (19A512f)**
**rvm ruby 2.6.3**

```zsh
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/oj-3.8.1/ext/oj
/Users/sharevari/.rvm/rubies/ruby-2.6.3/bin/ruby -I /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190723-39261-huj92x.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.6.3 on x86_64-darwin19 <<<<<
checking for rb_time_timespec()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/sharevari/.rvm/rubies/ruby-2.6.3/bin/$(RUBY_BASE_NAME)
	--with-oj-dir
	--without-oj-dir
	--with-oj-include
	--without-oj-include=${oj-dir}/include
	--with-oj-lib
	--without-oj-lib=${oj-dir}/lib
/Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:1069:in `block in have_func'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /Users/sharevari/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:1068:in `have_func'
	from extconf.rb:26:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/extensions/x86_64-darwin-19/2.6.0/oj-3.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/gems/oj-3.8.1 for inspection.
Results logged to /Users/sharevari/.rvm/gems/ruby-2.6.3@honshu/extensions/x86_64-darwin-19/2.6.0/oj-3.8.1/gem_make.out

An error occurred while installing oj (3.8.1), and Bundler cannot continue.
Make sure that `gem install oj -v '3.8.1' --source 'https://rubygems.org/'` succeeds before bundling.
```

**Comment by Fudoshiki** [comment]
Fixed by xcode-select --install
