### ISSUE TITLE
Time parser division by zero crash

### ISSUE THREAD

**Issue by Becojo** [ohler55/oj#554]
Running the following code triggers a crash.

```ruby
require 'oj'
Oj.load('{"^t":0.0000000000000000000000000000000000000000000000000000000000000000}')
```

Stack trace
```
Program received signal SIGFPE, Arithmetic exception.
0x00007fb3b257cc6f in hat_num (ni=0x7ffc6b8b65a0, kval=0x7ffc6b8b7c98, parent=0x7ffc6b8b7c98, pi=0x7ffc6b8b6a40) at object.c:280
280			int64_t	nsec = ni->num * 1000000000LL / ni->div;

#0  0x00007fb3b257cc6f in hat_num (ni=0x7ffc6b8b65a0, kval=0x7ffc6b8b7c98, parent=0x7ffc6b8b7c98, pi=0x7ffc6b8b6a40) at object.c:280
#1  hash_set_num (pi=0x7ffc6b8b6a40, kval=0x7ffc6b8b7c98, ni=<optimized out>) at object.c:521
#2  0x00007fb3b2584207 in read_num (pi=pi@entry=0x7ffc6b8b6a40) at parse.c:517
#3  0x00007fb3b25852f0 in oj_parse2 (pi=pi@entry=0x7ffc6b8b6a40) at parse.c:692
#4  0x00007fb3b2585db9 in protect_parse (pip=pip@entry=140722112784960) at parse.c:867
#5  0x00007fb3b6452de9 in rb_protect (proc=proc@entry=0x7fb3b2585db0 <protect_parse>, data=data@entry=140722112784960, pstate=pstate@entry=0x7ffc6b8b694c) at eval.c:1034
#6  0x00007fb3b2585eee in oj_pi_parse (argc=argc@entry=1, argv=argv@entry=0x7fb3b6a18048, pi=pi@entry=0x7ffc6b8b6a40, json=json@entry=0x0, len=len@entry=0, yieldOk=yieldOk@entry=1) at parse.c:976
#7  0x00007fb3b257d59b in oj_object_parse (argc=1, argv=0x7fb3b6a18048, self=<optimized out>) at object.c:745
#8  0x00007fb3b65d76ff in vm_call_cfunc_with_frame (ci=0x55aa3bf64790, cc=<optimized out>, calling=<optimized out>, reg_cfp=0x7fb3b6b17fa0, ec=0x55aa3bc059e8) at vm_insnhelper.c:1908
#9  vm_call_cfunc (ec=0x55aa3bc059e8, reg_cfp=0x7fb3b6b17fa0, calling=<optimized out>, ci=0x55aa3bf64790, cc=<optimized out>) at vm_insnhelper.c:1924
#10 0x00007fb3b65eb423 in vm_call_method (ec=0x55aa3bc059e8, cfp=0x7fb3b6b17fa0, calling=<optimized out>, ci=<optimized out>, cc=<optimized out>) at vm_insnhelper.c:2397
#11 0x00007fb3b65e0e1a in vm_exec_core (ec=ec@entry=0x55aa3bc059e8, initial=initial@entry=0) at insns.def:765
#12 0x00007fb3b65e74ac in rb_vm_exec (ec=0x55aa3bc059e8, mjit_enable_p=mjit_enable_p@entry=1) at vm.c:1885
#13 0x00007fb3b65ec950 in rb_iseq_eval_main (iseq=iseq@entry=0x55aa3bf7eac8) at vm.c:2144
#14 0x00007fb3b644f8aa in ruby_exec_internal (n=0x55aa3bf7eac8) at eval.c:262
#15 0x00007fb3b645189d in ruby_exec_node (n=<optimized out>, n@entry=0x55aa3bf7eac8) at eval.c:326
#16 0x00007fb3b645588e in ruby_run_node (n=0x55aa3bf7eac8) at eval.c:318
#17 0x000055aa3a7de9eb in main (argc=<optimized out>, argv=<optimized out>) at ./main.c:42
```

You can reproduce using the Ruby 2.6 docker image:
```
docker run --rm -it ruby:2.6 bash
gem install oj # Fetching oj-3.9.0.gem
irb
require 'oj'
Oj.load('{"^t":0.0000000000000000000000000000000000000000000000000000000000000000}') # Floating point exception
```

**Comment by ohler55** [comment]
There is a fix in the develop branch. Please give it a try. If all looks good I'll make a release.

**Comment by Becojo** [comment]
Seems good to prevent the crash.

**Comment by ohler55** [comment]
Released. Okay to close?
