### ISSUE TITLE
missing dependency on `bigdecimal`

### ISSUE THREAD

**Issue by and0x000** [ohler55/oj#613]
the gem `bigdecimal` is expected by oj but is not listed as a dependency.

https://github.com/ohler55/oj/blob/develop/lib/oj.rb#L8

This can become a problem, as it is not necessarily part of ruby, e.g. in alpine.

steps to reproduce:
```
docker run --rm -ti alpine:edge /bin/sh
/ # apk --update add ruby ruby-dev build-base
/ # ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
/ # gem list | grep bigdecimal
/ # gem install oj
Fetching oj-3.10.8.gem
Building native extensions. This could take a while...
Successfully installed oj-3.10.8
1 gem installed
/ # gem list | grep bigdecimal
/ # gem install pry
Fetching coderay-1.1.3.gem
Fetching pry-0.13.1.gem
Fetching method_source-1.0.0.gem
Successfully installed coderay-1.1.3
Successfully installed method_source-1.0.0
Successfully installed pry-0.13.1
3 gems installed
/ # pry 
[1] pry(main)> require 'oj'
LoadError: cannot load such file -- bigdecimal
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Caused by LoadError: cannot load such file -- oj
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

**Comment by ohler55** [comment]
Can you verify that adding a dependency in oj.gemspec for bigdecimal fixes the issue for you? If so I'll update that file and release.

**Comment by and0x000** [comment]
thank you for the quick response. Yes, adding it as a dependency to `oj.gemspec` fixes the problem.

```
/git # gem install oj-3.10.8.gem # gemfile built with dependency
Fetching bigdecimal-2.0.0.gem
Building native extensions. This could take a while...
Successfully installed bigdecimal-2.0.0
Building native extensions. This could take a while...
Successfully installed oj-3.10.8
2 gems installed
/git # pry
[1] pry(main)> require 'oj'
=> true
```

**Comment by ohler55** [comment]
Great, thanks. I'll make a new release later today. I assume the addition was:

```ruby
  s.add_dependency 'bigdecimal', '>= 0`
```

If not what version or line did you add?

**Comment by and0x000** [comment]
I used `s.add_runtime_dependency` but iirc this is just an alias for `s.add_dependency`. I did not specify any version, so the latest `bigdecimal` (2.0.0) was added.

**Comment by ohler55** [comment]
Thanks, will add:

```ruby
  s.add_dependency 'bigdecimal'
```

**Comment by ohler55** [comment]
Released.

**Comment by ohler55** [comment]
@and0x000 can you see if the current develop branch works for you?

**Comment by ohler55** [comment]
Released a new version
