### ISSUE TITLE
v3.11.7 Problems with Mac M1

### ISSUE THREAD

**Issue by jeduardo824** [ohler55/oj#666]
Hey, good afternoon.

Today, after updating the Oj to version 3.11.7, I faced a problem with `dlopen` in my Macbook M1.

![image](https://user-images.githubusercontent.com/27960597/123477647-b74d1f80-d5d4-11eb-9a84-ff897e89d1b1.png)

I was trying to investigate the cause, but I was not able to get a conclusion.

Reverting to version 3.11.6 worked perfectly

Any thoughts?

**Comment by ohler55** [comment]
The change was pretty minimal. I don't see how it would make a difference. I don't have an M1... yet. It is odd that the complaint is that the bundle is the wrong architecture. Are you building or copying from different machines? I would delete the oj.bundle and do a make clean and try again.

**Comment by Sauloxd** [comment]
I has some issues when bumping to 3.11.7 as well.
I'm running macOS Big Sur and had the following error log:
<details>
<summary>When installing gem</summary>
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/saulofuruta/.rvm/gems/ruby-2.7.3@qultureapp/gems/oj-3.11.7/ext/oj
/Users/saulofuruta/.rvm/rubies/ruby-2.7.3/bin/ruby -I /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0 -r
./siteconf20210627-2908-1lxqpwv.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.7.3 on x86_64-darwin19 <<<<<
checking for rb_time_timespec()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/saulofuruta/.rvm/rubies/ruby-2.7.3/bin/$(RUBY_BASE_NAME)
	--with-oj-dir
	--without-oj-dir
	--with-oj-include
	--without-oj-include=${oj-dir}/include
	--with-oj-lib
	--without-oj-lib=${oj-dir}/lib
/Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file.
(RuntimeError)
You have to install development tools first.
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:794:in `try_func'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:1083:in `block in have_func'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /Users/saulofuruta/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/mkmf.rb:1082:in `have_func'
	from extconf.rb:26:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/saulofuruta/.rvm/gems/ruby-2.7.3@qultureapp/extensions/x86_64-darwin-19/2.7.0/oj-3.11.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/saulofuruta/.rvm/gems/ruby-2.7.3@qultureapp/gems/oj-3.11.7 for inspection.
Results logged to /Users/saulofuruta/.rvm/gems/ruby-2.7.3@qultureapp/extensions/x86_64-darwin-19/2.7.0/oj-3.11.7/gem_make.out

An error occurred while installing oj (3.11.7), and Bundler cannot continue.
Make sure that `gem install oj -v '3.11.7' --source 'https://rubygems.org/'` succeeds before bundling.

</details>



And in the `gem_make.out` file, I had a log telling me the following error (sorry after I made it work, I lost the error log):
`xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist...`
But after following [this tip from SO](https://stackoverflow.com/a/57342129), it worked
Hope it helps others to bump this gem :)

**Comment by jeduardo824** [comment]
@ohler55 Thanks for the quick response! 
The problem was with tmux. 
When I ran `uname -m` in my tmux environment, it showed `x86_64` instead of `arm64`. 
Once I got out tmux and reinstalled the `oj` in a regular terminal window, it worked (even inside tmux).

**Comment by ohler55** [comment]
Glad you found the issue.

**Comment by philipbjorge** [comment]
@jeduardo824 -- Thanks for sharing these details.

We ran into the same issue with a developer running `bundle` from within the RubyMine terminal. It's unclear to us if this is a bug in the IDE or maybe they have the x86_64 version of RubyMine installed or something.

Regardless, your instructions helped us pinpoint and resolve the issue and cause! Cheers!
