### ISSUE TITLE
Version 3.13.0 can't be installed on Windows ('gettimeofday' conflicting types)

### ISSUE THREAD

**Issue by bodrovis** [ohler55/oj#688]
The issue described in #94 is back with 3.13.0 - probably, because a new parser has been introduced. I'm observing this on Windows 10x64 with Ruby 2.7 and 3.0 (and the latest mingw toolchain):

```
make DESTDIR\=
generating oj-x64-mingw32.def
compiling cache.c
compiling cache8.c
compiling circarray.c
compiling code.c
compiling compat.c
compiling custom.c
compiling debug.c
compiling dump.c
compiling dump_compat.c
compiling dump_leaf.c
compiling dump_object.c
compiling dump_strict.c
compiling err.c
compiling fast.c
fast.c: In function 'parse_json':
fast.c:776:20: warning: array subscript -16384 is outside array bounds of 'struct _parseInfo[1]' [-Warray-bounds]
  776 |     pi.stack_min = (void *)((char *)&pi - (512 * 1024));
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fast.c:752:23: note: while referencing 'pi'
  752 |     struct _parseInfo pi;
      |                       ^~
compiling hash_test.c
compiling intern.c
compiling mimic_json.c
compiling object.c
compiling odd.c
compiling oj.c
compiling parse.c
compiling parser.c
In file included from parser.c:18:
C:/Ruby30-x64/msys64/mingw64/x86_64-w64-mingw32/include/sys/time.h:42:13: error: conflicting types for 'gettimeofday'
   42 | int __cdecl gettimeofday(struct timeval *__restrict__,
      |             ^~~~~~~~~~~~
In file included from C:/Ruby30-x64/include/ruby-3.0.0/ruby/internal/dosish.h:38,
                 from C:/Ruby30-x64/include/ruby-3.0.0/ruby/defines.h:79,
                 from C:/Ruby30-x64/include/ruby-3.0.0/ruby/ruby.h:23,
                 from C:/Ruby30-x64/include/ruby-3.0.0/ruby.h:38,
                 from parser.h:8,
                 from parser.c:3:
C:/Ruby30-x64/include/ruby-3.0.0/ruby/win32.h:304:12: note: previous declaration of 'gettimeofday' was here
  304 | extern int gettimeofday(struct timeval *, struct timezone *);
      |            ^~~~~~~~~~~~
make: *** [Makefile:245: parser.o] Error 1

make failed, exit code 2
```

**Comment by bodrovis** [comment]
Please let me know if any further info is needed 😇

**Comment by ohler55** [comment]
I might if I can't get the windows CI working. Would you be able to try out branches with potential fixes?

**Comment by bodrovis** [comment]
Yes, sure. I'm not very good with C lang though :)

**Comment by ohler55** [comment]
Quite alright. It would only be to run the tests and give me the results.

The gettimeofday issue really looks to be an environmental one though where the mingw64 has a conflict with ruby and I'm not sure how to deal with that one other than to avoid using it.

**Comment by ohler55** [comment]
Pushed a version to the develop branch. If it builds in Windows I'll make a release.

**Comment by dvanfleet** [comment]
I'm experiencing this issue as well on Windows 10 with Ruby 2.6.6. Thanks for working on the fix, @ohler55 !

**Comment by bodrovis** [comment]
@ohler55 Well, for now I've tried to include the new version to my Gemfile: `gem 'oj', github: 'ohler55/oj', branch: 'develop'`. However, it does not seem to fix the issue so far:

```
Using oj 3.13.1 from https://github.com/ohler55/oj.git (at develop@d54e6e2)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby30-x64/lib/ruby/gems/3.0.0/bundler/gems/oj-d54e6e25b02c/ext/oj
C:/Ruby30-x64/bin/ruby.exe -I C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0 -r
./siteconf20210810-11636-5tia4v.rb extconf.rb
>>>>> Creating Makefile for ruby version 3.0.2 on x64-mingw32 <<<<<
checking for rb_time_timespec()... yes
checking for rb_ivar_count()... yes
checking for rb_ivar_foreach()... yes
checking for rb_gc_mark_movable()... yes
checking for stpcpy()... no
checking for pthread_mutex_init()... yes
checking for rb_enc_associate()... yes
checking for rb_ext_ractor_safe() in ruby.h... yes
checking for rb_hash_bulk_insert() in ruby.h... yes
creating Makefile
rm: cannot remove 'mkmf.log': Device or resource busy
make: [Makefile:175: clean] Error 1 (ignored)

current directory:
C:/Ruby30-x64/lib/ruby/gems/3.0.0/bundler/gems/oj-d54e6e25b02c/ext/oj
make DESTDIR\= clean

current directory:
C:/Ruby30-x64/lib/ruby/gems/3.0.0/bundler/gems/oj-d54e6e25b02c/ext/oj
make DESTDIR\=
generating oj-x64-mingw32.def
compiling cache.c
compiling cache8.c
compiling circarray.c
compiling code.c
compiling compat.c
compiling custom.c
compiling debug.c
compiling dump.c
compiling dump_compat.c
compiling dump_leaf.c
compiling dump_object.c
compiling dump_strict.c
compiling err.c
compiling fast.c
fast.c: In function 'parse_json':
fast.c:774:20: warning: array subscript -16384 is outside array bounds of
'struct _parseInfo[1]' [-Warray-bounds]
  774 |     pi.stack_min = (void*)((char*)&pi - (512 * 1024));
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fast.c:750:23: note: while referencing 'pi'
  750 |     struct _parseInfo pi;
      |                       ^~
compiling intern.c
compiling mimic_json.c
compiling object.c
compiling odd.c
compiling oj.c
compiling parse.c
compiling parser.c
In file included from parser.c:18:
C:/Ruby30-x64/msys64/mingw64/x86_64-w64-mingw32/include/sys/time.h:42:13: error:conflicting types for 'gettimeofday'
   42 | int __cdecl gettimeofday(struct timeval *__restrict__,
      |             ^~~~~~~~~~~~
In file included from
C:/Ruby30-x64/include/ruby-3.0.0/ruby/internal/dosish.h:38,
                 from C:/Ruby30-x64/include/ruby-3.0.0/ruby/defines.h:79,
                 from C:/Ruby30-x64/include/ruby-3.0.0/ruby/ruby.h:23,
                 from C:/Ruby30-x64/include/ruby-3.0.0/ruby.h:38,
                 from parser.h:8,
                 from parser.c:3:
C:/Ruby30-x64/include/ruby-3.0.0/ruby/win32.h:304:12: note: previous declarationof 'gettimeofday' was here
  304 | extern int gettimeofday(struct timeval *, struct timezone *);
      |            ^~~~~~~~~~~~
make: *** [Makefile:245: parser.o] Error 1

make failed, exit code 2

Gem files will remain installed in
C:/Ruby30-x64/lib/ruby/gems/3.0.0/bundler/gems/oj-d54e6e25b02c for inspection.
Results logged to
C:/Ruby30-x64/lib/ruby/gems/3.0.0/bundler/gems/extensions/x64-mingw32/3.0.0/oj-d54e6e25b02c/gem_make.out

  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:92:in `run'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:43:in `block in
make'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:35:in `each'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:35:in `make'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:63:in
`block in build'
  C:/Ruby30-x64/lib/ruby/3.0.0/tempfile.rb:317:in `open'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in
`build'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:158:in
`build_extension'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:192:in `block
in build_extensions'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:189:in `each'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:189:in
`build_extensions'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:828:in
`build_extensions'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/rubygems_gem_installer.rb:66:in
`build_extensions'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/source/path/installer.rb:34:in
`post_install'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/source/path.rb:244:in
`generate_bin'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/source/git.rb:186:in `install' C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:171:in
`install_serially'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:97:in
`call'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer/parallel_installer.rb:71:in
`call'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:263:in
`install_in_parallel'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:210:in `install'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:90:in `block in
run'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:12:in `block in
lock'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:9:in `open'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/process_lock.rb:9:in `lock'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:72:in `run'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/installer.rb:24:in `install'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli/update.rb:74:in `run'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:308:in `block in update'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/settings.rb:131:in `temporary'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:307:in `update'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in
`run'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in
`invoke_command'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in
`dispatch'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in
`start'
  C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.25/exe/bundle:49:in `block
in <top (required)>'
C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:128:in
`with_friendly_errors'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.25/exe/bundle:37:in `<top
(required)>'
  C:/Ruby30-x64/bin/bundle:23:in `load'
  C:/Ruby30-x64/bin/bundle:23:in `<main>'
```

**Comment by bodrovis** [comment]
More or less the same happens with Ruby 2.7:

```
In file included from parser.c:18:
C:/Ruby27/msys64/mingw64/x86_64-w64-mingw32/include/sys/time.h:42:13: error:
conflicting types for 'gettimeofday'
   42 | int __cdecl gettimeofday(struct timeval *__restrict__,
      |             ^~~~~~~~~~~~
In file included from C:/Ruby27/include/ruby-2.7.0/ruby/defines.h:371,
                 from C:/Ruby27/include/ruby-2.7.0/ruby/ruby.h:29,
                 from C:/Ruby27/include/ruby-2.7.0/ruby.h:33,
                 from parser.h:8,
                 from parser.c:3:
C:/Ruby27/include/ruby-2.7.0/ruby/win32.h:318:12: note: previous declaration of 'gettimeofday' was here
  318 | extern int gettimeofday(struct timeval *, struct timezone *);
      |            ^~~~~~~~~~~~
make: *** [Makefile:245: parser.o] Error 1
```

**Comment by bodrovis** [comment]
So, that's the line, I believe?.. https://github.com/ohler55/oj/blob/1deb721c6e2f6d3fc056f312db21df4d0f9777ab/ext/oj/parser.c#L18 Can we somehow not include it on windows based on some condition?

**Comment by ohler55** [comment]
Unused include file removed from parser.c

**Comment by bodrovis** [comment]
@ohler55 Yes, it works now on Ruby 2.7 and 3.0!

**Comment by ohler55** [comment]
Great. I'll make a release.

**Comment by ohler55** [comment]
Released!

**Comment by dvanfleet** [comment]
@ohler55 It's fixed for me when I run `bundle update`. Thanks!

**Comment by bodrovis** [comment]
@ohler55 Thank you so much for a quick fix, and for all the hard work on this solution - I use it in all my gems related to JSON data 😄
