### ISSUE TITLE
3.13.3 breaks aws-sdk-core on macos

### ISSUE THREAD

**Issue by modosc** [ohler55/oj#700]
when upgrading from `3.13.2` to `3.13.3` our codebase stopped working on macos:
```
/Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/api/customizations.rb:60:in `is_eventstream?': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/api/customizations.rb:52:in `block in exclude_eventstream'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/api/customizations.rb:50:in `each'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/api/customizations.rb:50:in `exclude_eventstream'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/api/customizations.rb:30:in `apply_api_customizations'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/api/builder.rb:28:in `customize'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/api/builder.rb:12:in `build'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/client.rb:47:in `define'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core.rb:658:in `block in <module:Aws>'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core.rb:648:in `block in add_service'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core.rb:647:in `each'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core.rb:647:in `add_service'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/s3.rb:1:in `<top (required)>'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/jonathan.schatz/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
```
i can't share the rest of the stack trace but the next line included a reference to `Aws::S3::Object` which triggered the above autoloading.

this doesn't seem to be an issue on linux because our tests and code happily run there. 

reverting to 3.13.2 resolves this.

**Comment by ohler55** [comment]
I don't see any mention of the Oj in the stack. Is there anything else you can tell me about the failure?

**Comment by modosc** [comment]
sure, i'll put an example together tomorrow

**Comment by ohler55** [comment]
This might be the same as #699 . The "thread-protect" branch might have the fix if you want to try it.

**Comment by modosc** [comment]
`thread-protect` works for us, i'll close this and track the other issue. thanks!

**Comment by ohler55** [comment]
Thanks for checking. You were the first to let me know.
