### ISSUE TITLE
to_stream and nonblocking sockets

### ISSUE THREAD

**Issue by carlhoerberg** [ohler55/oj#723]
Since [Ruby 3.0 sockets are by default nonblocking](https://bugs.ruby-lang.org/issues/17664), which causes issues for `Oj.to_stream` [here](https://github.com/ohler55/oj/blob/7b9a95f2f07046c766b8bdb26829763d1b700578/ext/oj/dump.c#L690)

```ruby
require "oj"
require "socket"
require 'io/nonblock'
pid = spawn("nc -d 0.1 -l 5000", out: "/dev/null")
at_exit { Process.kill 9, pid }
sleep 0.1
s = Socket.tcp("localhost", 5000)
# s.nonblock = false
1_000_000.times do
  Oj.to_stream(s, { a: 1 })
end
```

output: 
```
n.rb:10:in `to_stream': Write failed. [11:Resource temporarily unavailable] (IOError)
        from n.rb:10:in `block in <main>'
        from n.rb:9:in `times'
        from n.rb:9:in `<main>'
```

set `s.nonblock = false` and it works as expected..

Not sure if something should be done in `Oj`, but could be good for ppl to be aware.. It's not very ergonomic to catch the generic `IOError` and then trying to figure out if it's a `EAGAIN` error and manually do `IO.select`.

**Comment by carlhoerberg** [comment]
Maybe use `pwritev2` with the `RWF_SYNC` flag, but that's Linux only.. https://man7.org/linux/man-pages/man2/pwritev2.2.html

**Comment by ohler55** [comment]
I'm hesitant to make that the default but it would be a nice option for `Oj.to_stream`. What do you think?

**Comment by ohler55** [comment]
Looking at this again. I think I misunderstood the desired changes. I don't think Oj should set the stream to non blocking but I do think Oj could handle EAGAIN errors along with some timeout value. I'm looking into that now.

**Comment by ohler55** [comment]
Please try branch "non-blocking". Test added as well although I found the issue is exposed more readily with a large single write instead of many smaller ones and the test reflects that.

**Comment by ohler55** [comment]
I believe the non-blocking branch fixes the issue. I plan to release tomorrow barring feedback from you indicating it is not fixed.

**Comment by ohler55** [comment]
Okay to close?

**Comment by carlhoerberg** [comment]
is the patch included in oj 3.13.11, because the example in the original issue still fails with it
