### ISSUE TITLE
`require 'oj'` on TruffleRuby 22.2.0 causes `Polyglot::ForeignException`

### ISSUE THREAD

**Issue by okuramasafumi** [ohler55/oj#796]
```
irb(main):3.0.3:003:0> require 'oj'
/Users/okuramasafumi/.gem/truffleruby/3.0.3/gems/oj-3.13.18/ext/oj/parse.c:246:in `oj_scanner_init': External LLVMFunction __cpu_indicator_init cannot be found. (Polyglot::ForeignException)
	from /Users/okuramasafumi/.gem/truffleruby/3.0.3/gems/oj-3.13.18/ext/oj/oj.c:1753:in `Init_oj'
	from <internal:/Users/okuramasafumi/.rubies/truffleruby-22.2.0/lib/mri/rubygems/core_ext/kernel_require.rb>:64:in `<unknown>'
	from <internal:/Users/okuramasafumi/.rubies/truffleruby-22.2.0/lib/mri/rubygems/core_ext/kernel_require.rb>:64:in `Kernel#gem_original_require'
	from <internal:/Users/okuramasafumi/.rubies/truffleruby-22.2.0/lib/mri/rubygems/core_ext/kernel_require.rb>:64:in `Kernel#require'
	from /Users/okuramasafumi/.gem/truffleruby/3.0.3/gems/oj-3.13.18/lib/oj.rb:13:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `Kernel#gem_original_require'
	from <internal:/Users/okuramasafumi/.rubies/truffleruby-22.2.0/lib/mri/rubygems/core_ext/kernel_require.rb>:139:in `Kernel#require'
	from (irb):1:in `<top (required)>'
	from <internal:core> core/kernel.rb:407:in `Kernel#loop'
	from <internal:core> core/throw_catch.rb:36:in `Kernel#catch'
	from <internal:core> core/throw_catch.rb:36:in `Kernel#catch'
	from /Users/okuramasafumi/.rubies/truffleruby-22.2.0/lib/gems/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from <internal:core> core/kernel.rb:376:in `Truffle::KernelOperations.load'
	from <internal:core> core/kernel.rb:376:in `Kernel#load'
	from /Users/okuramasafumi/.rubies/truffleruby-22.2.0/bin/irb:42:in `<main>'
```

On TruffleRuby version 22.2.0, `require 'oj'` causes `Polyglot::ForeignException`.
I was not sure if I should post an issue on Oj or TruffleRuby, but I found the function call was recently added by 91376b92.

**Comment by ohler55** [comment]
Debugging that issue is going to require looking into why the environment doesn't pick up the oj_scanner_init function. I'll see what I can do just by looking at the code but could use some help from someone, maybe you, to provide some information on truffle ruby.

**Comment by stanhu** [comment]
https://github.com/ohler55/oj/pull/797 might fix this. Let me see if I can verify with a Docker image.

**Comment by stanhu** [comment]
Using https://hub.docker.com/r/flavorjones/truffleruby, I see that #797 fixes that warning, but now I get:

```
##########################################################################################
ruby test/tests.rb -v && ruby test/tests_mimic.rb -v && ruby test/tests_mimic_addition.rb -v
/oj/ext/oj/parse.c:237:in `cpu_supports_sse42': External LLVMFunction __cpu_indicator_init cannot be found. (com.oracle.truffle.llvm.runtime.except.LLVMLinkerException) (RuntimeError)
Translated to internal error
	from /oj/ext/oj/parse.c:247:in `oj_scanner_init'
	from /oj/ext/oj/oj.c:2046:in `Init_oj'
	from /usr/local/lib/mri/rubygems/core_ext/kernel_require.rb:83:in `gem_original_require'
	from /usr/local/lib/mri/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /oj/lib/oj.rb:13:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /usr/local/lib/mri/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /oj/test/test_compat.rb:15:in `<top (required)>'
	from <internal:core> core/kernel.rb:260:in `require'
	from test/tests.rb:10:in `<main>'
```

**Comment by stanhu** [comment]
#797 and #798 should help here.

There are some test failures with Truffleruby that seem present even in `v3.13.14`:

[oj-3.13.14.txt](https://github.com/ohler55/oj/files/9204120/oj-3.13.14.txt)

Here is the latest test run with #797 and #798:

[oj-master-with-fixes.txt](https://github.com/ohler55/oj/files/9204119/oj-master-with-fixes.txt)
