### ISSUE TITLE
Upgrading to 3.13.22 fails

### ISSUE THREAD

**Issue by kapso** [ohler55/oj#822]
```
Installing oj 3.13.22 (was 3.13.21) with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/oj-3.13.22/ext/oj
/Users/kapil/.rbenv/versions/3.1.2/bin/ruby -I /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0 -r ./siteconf20221103-83405-59k9h8.rb extconf.rb
>>>>> Creating Makefile for ruby version 3.1.2 on x86_64-darwin21 <<<<<
checking for rb_gc_mark_movable()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/kapil/.rbenv/versions/3.1.2/bin/$(RUBY_BASE_NAME)
	--with-oj-dir
	--without-oj-dir
	--with-oj-include
	--without-oj-include=${oj-dir}/include
	--with-oj-lib
	--without-oj-lib=${oj-dir}/lib
/Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:830:in `try_func'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:1119:in `block in have_func'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:332:in `open'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:332:in `open'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/mkmf.rb:1118:in `have_func'
	from extconf.rb:27:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/extensions/x86_64-darwin-21/3.1.0/oj-3.13.22/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/oj-3.13.22 for inspection.
Results logged to /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/extensions/x86_64-darwin-21/3.1.0/oj-3.13.22/gem_make.out

  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/worker.rb:62:in `apply_func'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/worker.rb:54:in `loop'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/worker.rb:54:in `process_queue'
  /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing oj (3.13.22), and Bundler cannot continue.
```

**Comment by chuckphillips** [comment]
I'm seeing the same issue

**Comment by ohler55** [comment]
I'll look into it this weekend. It seems odd since it was mostly moving functions around.

**Comment by chuckphillips** [comment]
`xcode-select --install` fixed the issue for me.

**Comment by ohler55** [comment]
@kapso did you try updating xcode?

**Comment by kapso** [comment]
@ohler55 `xcode-select --install` fixed the issue for me
