### ISSUE TITLE
StreamWriter with subprocess - Undefined error: 0

### ISSUE THREAD

**Issue by jscheid** [ohler55/oj#943]
Hi, thanks for oj - we've been using it for many years without problems, it's been rock solid.

We're now trying to pipe directly into stdin of a subprocess using `Oj::StreamWriter`, but we're running into I/O errors. I've put together a minimal test case here: https://github.com/jscheid/oj-subprocess-test

On macOS 14.7.1 with ruby 3.3.0 it consistently outputs the following:

```
$ bundle exec ruby test.rb
pushed chunk 0
pushed chunk 1
<SNIP>
pushed chunk 20
test.rb:18:in `push_json': Write failed. [_0_:Undefined error: 0] (IOError)
	from test.rb:18:in `block in <main>'
	from <internal:numeric>:237:in `times'
	from test.rb:17:in `<main>'
```

On Linux with ruby 3.3.1 the error is slightly different, here the message is `Write failed. [_0_:Success]`

With slightly different test data I've also witnessed (on macOS) `Write failed. [_25_:Inappropriate ioctl for device]`

With a larger `buffer_size` the error occurs later - it appears to occur just when the buffer is full. However, if I add `writer.flush` after every push, surprisingly it doesn't fail the first time `flush` is called.

All seems to work fine when writing the JSON data directly using `IO.write` calls, code for this is also included in the test case (toggle the if statement.) This leads me to believe that it isn't a problem with the `subprocess` gem (which we've also been using for years without issues.)

I've also tried simulating oj's buffering by writing it all with one single `IO.write` but that doesn't fail either.

Is anyone able to reproduce this? Is there perhaps some setting that we're missing or something else that's obvious?

**Comment by jscheid** [comment]
I believe the issue is here: https://github.com/ohler55/oj/blob/c70bf4125b546bc7146840b15de36460d42b4dff/ext/oj/stream_writer.c#L57-L59

The [write(2) man page](https://man7.org/linux/man-pages/man2/write.2.html) says:
> On success, the number of bytes written is returned.  On error, -1 is returned, and [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to indicate the error.
>
>  Note that a successful write() may transfer fewer than count bytes.  Such partial writes can occur for various reasons [...] In the event of a partial write, the caller can make another write() call to transfer the remaining bytes.  The subsequent call will either transfer further bytes or may result in an error (e.g., if the disk is now full).
